[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vaihtaa_api"
version = "0.1.0"
description = "Economy connection package"
requires-python = ">=3.7"